module.exports.descriptors = [
  "Forest",
  "Ancient",
  "Petrified",
  "Roaring",
  "Cascade",
  "Tumbling",
  "Silent",
  "Redwood",
  "Bullfrog",
  "Maple",
  "Misty",
  "Elk",
  "Grizzly",
  "Ocean",
  "Sea",
  "Sky",
  "Dusty",
  "Diamond",
];

module.exports.places = [
  "Flats",
  "Village",
  "Canyon",
  "Pond",
  "Group Camp",
  "Horse Camp",
  "Ghost Town",
  "Camp",
  "Dispersed Camp",
  "Backcountry",
  "River",
  "Creek",
  "Creekside",
  "Bay",
  "Spring",
  "Bayshore",
  "Sands",
  "Mule Camp",
  "Hunting Camp",
  "Cliffs",
  "Hollow",
];

module.exports.description = [
  "Escape the hustle and bustle of the city at this peaceful campground surrounded by towering trees.",
  "Discover the beauty of the desert at this remote campground, where you can stargaze to your heart's content.",
  "Set up camp at the foot of a majestic mountain range and explore the rugged terrain by day.",
  "This pet-friendly campground has plenty of space for your furry friends to run and play.",
  "Enjoy the tranquil sounds of a babbling brook at this charming campground tucked away in the woods.",
  "Experience the thrill of whitewater rafting and then unwind at this cozy campground along the riverbank.",
  "Bring your own boat and dock it at this lakeside campground, where you can fish and swim to your heart's content.",
  "Get back to basics at this minimalist campground, where you can disconnect from technology and reconnect with nature.",
  "Located just a stone's throw from a scenic hiking trail, this campground is a nature lover's paradise.",
  "Bring your telescope and marvel at the stars at this remote campground that boasts some of the darkest skies in the country.",
  "This family-friendly campground features a playground, basketball court, and plenty of activities to keep the kids entertained.",
  "Unwind in the shade of towering trees at this tranquil campground, where the sounds of nature lull you to sleep at night.",
  "Set up camp on the banks of a picturesque river and cast your line for a chance to catch some fish.",
  "This eco-friendly campground is powered entirely by solar energy, making it the perfect choice for eco-conscious campers.",
  "Stay in a cozy cabin at this rustic campground, where you can enjoy all the comforts of home while still getting back to nature.",
  "Take in breathtaking views of the surrounding mountains at this scenic campground, which is situated at a high elevation.",
  "This rustic campground is the perfect choice for backpackers who want to get off the beaten path and explore remote wilderness areas.",
  "Enjoy a barbecue under the stars at this spacious campground, which features picnic tables and fire pits for your convenience.",
  "Stay cool during the hot summer months at this shady campground, where the trees provide plenty of natural shade.",
  "Bring your RV and park it at this well-equipped campground, which features full hookups and amenities like showers and laundry facilities.",
  "Situated in the heart of wine country, this charming campground is the perfect base for exploring nearby vineyards.",
  "This secluded campground is only accessible by foot or boat, making it a true wilderness experience.",
  "Pitch your tent at this beachside campground, where you can fall asleep to the sound of crashing waves.",
  "Take a dip in the crystal-clear waters of the lake at this waterfront campground, which also features a sandy beach for sunbathing.",
  "This campground is a paradise for birdwatchers, with dozens of species of birds to spot in the surrounding trees and fields.",
];

module.exports.images = [
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1674059712/Yelp-Camp/scott-goodwill-y8Ngwq34_Ak-unsplash_xoakbn.jpg",
    filename: "Yelp-Camp/scott-goodwill-y8Ngwq34_Ak-unsplash_xoakbn",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1674059712/Yelp-Camp/zach-betten-K9olx8OF36A-unsplash_1_qbe2cx.jpg",
    filename: "Yelp-Camp/zach-betten-K9olx8OF36A-unsplash_1_qbe2cx",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1674136433/Yelp-Camp/avyn1qbyli88tswj6l22.jpg",
    filename: "avyn1qbyli88tswj6l22",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1674136433/Yelp-Camp/ennpjdmvmoplu2mrchhs.jpg",
    filename: "ennpjdmvmoplu2mrchhs",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1674136941/Yelp-Camp/noho5brwamadgqx9xlpf.jpg",
    filename: "noho5brwamadgqx9xlpf",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726357/Yelp-Camp/pt44amtnlb6moxhoeedf.jpg",
    filename: "pt44amtnlb6moxhoeedf",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726363/Yelp-Camp/aycjs7ywvjxuqwmlbg5n.jpg",
    filename: "aycjs7ywvjxuqwmlbg5n",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726536/Yelp-Camp/cbz3s6pgzpsh1od7jqu8.jpg",
    filename: "cbz3s6pgzpsh1od7jqu8",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726544/Yelp-Camp/pohbwsdqcsqo1bzwj9sk.jpg",
    filename: "pohbwsdqcsqo1bzwj9sk",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726736/Yelp-Camp/xhtmpc5ewr4rw1uepau9.jpg",
    filename: "xhtmpc5ewr4rw1uepau9",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726749/Yelp-Camp/vcwkeigkrgkym6fsbnbh.jpg",
    filename: "xhtmpc5ewr4rw1uepau9",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726536/Yelp-Camp/cbz3s6pgzpsh1od7jqu8.jpg",
    filename: "cbz3s6pgzpsh1od7jqu8",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726544/Yelp-Camp/pohbwsdqcsqo1bzwj9sk.jpg",
    filename: "pohbwsdqcsqo1bzwj9sk",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726736/Yelp-Camp/xhtmpc5ewr4rw1uepau9.jpg",
    filename: "xhtmpc5ewr4rw1uepau9",
  },
  {
    url: "https://res.cloudinary.com/dyjb0amlp/image/upload/v1678726749/Yelp-Camp/vcwkeigkrgkym6fsbnbh.jpg",
    filename: "xhtmpc5ewr4rw1uepau9",
  },
];
